# Configuration for the Twinings 2k16

# Site settings
title: The Twinings
description: >
  Brown's Computer Science Department presents 
  the 8th annual Twinings Awards for 
  ~distinguished~ seniors.
baseurl: ""
permalink: /:title/ #posts
url: "http://thetwinings.org/"
logo: assets/Logo.png

# Build settings
markdown: kramdown
