# Configuration for the Twinings 2k16

# Site settings
title: The Twinings
description: >
  Brown's Computer Science Department presents 
  the 8th annual Twinings Awards for 
  ~distinguished~ seniors.
baseurl: ""
permalink: /:title/ #posts
url: "http://thetwinings.org/"
logo: assets/logo.png
date: "8pm on May 18th"
location: "The Delta Tau Estate: Olney on Wriston Quad"
intro: >
  The Academy humbly requests the honor of your presence for the
  Eighth Annual Twining Awards Ceremony. This unofficial Computer
  Science Department tradition, older than Andy and John Savage
  combined, is an awards ceremony for the senior class to highlight
  that which is significant in our department (and by significant, we
  mean nostalgic and/or meaningless).There will be snacks and
  champagne, as well as anything else you care to bring.
intromore: >
  Prepare an acceptance speech for the awards for which you are nominated. Formal attire required.
  Donations greatly appreciated; this is not a sponsored event. Venmo @AlexaVanHattum or cash to
  any of the Academy.


# Build settings
markdown: kramdown
