# frozen_string_literal: true
# Gemfile for DG
source "https://rubygems.org"

group :jekyll_plugins do
  gem 'emoji_for_jekyll'    # emoji support 💁
  gem 'hawkins'             # live reload!
  gem 'jekyll-press'        # minifies everything

  # CSS/SASS gems
  gem 'jekyll-autoprefixer' # autoprefixes css
  gem 'normalize-scss'   	# normalizes the scss
  gem 'susy'				# Susy grid framework
end